version: '3'
services:
  go:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/go/src/github.com/sys-cat/imageapi_for_advent2019
    working_dir: /go/src/github.com/sys-cat/imageapi_for_advent2019
    environment:
      - GO111MODULE=on
    ports:
      - "8080:8080"
    command: "go run main.go"